## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================
resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

- name: sles-gpdb-dev-11-beta
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git

- name: plr_src
  type: git
  source:
    branch: gpdb5_clean
    uri: https://github.com/greenplum-db/plr.git

# centos 7

- name: bin_r_centos7
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkg/r/bin_r_centos7.tar.gz


- name: bin_gpdb_centos7
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos7/bin_gpdb.tar.gz

- name: plr_gpdb_centos7_build
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkg/plr/build/plr-centos7.gppkg

- name: plr_gpdb_centos7_release
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: gppkg/plr/release/plr-ossv(.*)-rhel7-x86_64.gppkg

# centtos 6

- name: bin_r_centos6
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkg/r/bin_r_centos6.tar.gz

- name: bin_gpdb_centos6
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: plr_gpdb_centos6_build
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkg/plr/build/plr-centos6.gppkg

- name: plr_gpdb_centos6_release
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: gppkg/plr/release/plr-ossv(.*)-rhel6-x86_64.gppkg

# suse11

- name: bin_r_suse11
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkg/r/bin_r_suse11.tar.gz

- name: bin_gpdb_suse11
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_sles11/bin_gpdb.tar.gz

- name: plr_gpdb_suse11_build
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: gppkgs/gpdb/plr-suse11.gppkg

- name: plr_gpdb_suse11_release
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: gppkg/plr/release/plr-ossv(.*)-sles11-x86_64.gppkg

## ======================================================================
## jobs
## ======================================================================

jobs:

# Build R binaries

- name: Build_R_CENTOS7
  plan:
  - aggregate:
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos7
    - get: centos-gpdb-dev-7
  - task: r_centos7_build
    file: plr_src/concourse/tasks/build_r.yml
    image: centos-gpdb-dev-7
    output_mapping:
      bin_r: bin_r_centos7
    params:
      OSVER: centos7
  - put: bin_r_centos7
    params:
      file: bin_r_centos7/bin_r_centos7.tar.gz

- name: Build_R_CENTOS6
  plan:
  - aggregate:
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos6
    - get: centos-gpdb-dev-6
  - task: r_centos6_build
    file: plr_src/concourse/tasks/build_r.yml
    image: centos-gpdb-dev-6
    output_mapping:
      bin_r: bin_r_centos6
    params:
      OSVER: centos6
  - put: bin_r_centos6
    params:
      file: bin_r_centos6/bin_r_centos6.tar.gz

- name: Build_R_SUSE11
  plan:
  - aggregate:
    - get: plr_src
      trigger: true
    - get: bin_gpdb_suse11
    - get: sles-gpdb-dev-11-beta
  - task: r_suse11_build
    file: plr_src/concourse/tasks/build_r.yml
    image: sles-gpdb-dev-11-beta
    output_mapping:
      bin_r: bin_r_suse11
    params:
      OSVER: suse11
  - put: bin_r_suse11
    params:
      file: bin_r_suse11/bin_r_suse11.tar.gz


# Build PLR GPPKG

- name: plr_centos7_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
      passed: [Build_R_CENTOS7]
      trigger: true
    - get: bin_gpdb_centos7
    - get: bin_r_centos7
    - get: gpdb_src
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-7
      input_mapping:
        bin_gpdb: bin_gpdb_centos7
        bin_r: bin_r_centos7
      output_mapping:
        bin_plr: plr_gpdb_centos7_build
      params:
        OSVER: centos7
  - aggregate:
    - put: plr_gpdb_centos7_build
      params:
        file: plr_gpdb_centos7_build/plr-*.gppkg

- name: plr_centos6_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
      passed: [Build_R_CENTOS6]
      trigger: true
    - get: bin_gpdb_centos6
    - get: bin_r_centos6
    - get: gpdb_src
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-6
      input_mapping:
        bin_gpdb: bin_gpdb_centos6
        bin_r: bin_r_centos6
      output_mapping:
        bin_plr: plr_gpdb_centos6_build
      params:
        OSVER: centos6
  - aggregate:
    - put: plr_gpdb_centos6_build
      params:
        file: plr_gpdb_centos6_build/plr-*.gppkg

- name: plr_suse11_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: plr_src
      passed: [Build_R_SUSE11]
      trigger: true
    - get: sles-gpdb-dev-11-beta
    - get: bin_gpdb_suse11
    - get: bin_r_suse11
    - get: gpdb_src
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: sles-gpdb-dev-11-beta
      input_mapping:
        bin_gpdb: bin_gpdb_suse11
        bin_r: bin_r_suse11
      output_mapping:
        bin_plr: plr_gpdb_suse11_build
      params:
        OSVER: suse11
  - aggregate:
    - put: plr_gpdb_suse11_build
      params:
        file: plr_gpdb_suse11_build/plr-*.gppkg

# Test PL/R GPPKG

- name: plr_centos6_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
      passed: [plr_centos6_build]
      trigger: true
    - get: plr_gpdb_centos6_build
    - get: bin_gpdb_centos6
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
      bin_plr: plr_gpdb_centos6_build
    output_mapping:
        plr_gppkg: plr_gpdb_centos6_release
    params:
      OSVER: centos6
      GPGBVER: GPDB-5.0.0
  - put: plr_gpdb_centos6_release
    params:
      file: plr_gpdb_centos6_release/plr-*.gppkg

- name: plr_centos7_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
      passed: [plr_centos7_build]
      trigger: true
    - get: plr_gpdb_centos7_build
    - get: bin_gpdb_centos7
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
      bin_plr: plr_gpdb_centos7_build
    output_mapping:
      plr_gppkg: plr_gpdb_centos7_release
    params:
      OSVER: centos7
      GPGBVER: GPDB-5.0.0
  - put: plr_gpdb_centos7_release
    params:
      file: plr_gpdb_centos7_release/plr-*.gppkg

- name: plr_suse11_test
  plan:
  - aggregate:
    - get: sles-gpdb-dev-11-beta
    - get: plr_src
      passed: [plr_suse11_build]
      trigger: true
    - get: plr_gpdb_suse11_build
    - get: bin_gpdb_suse11
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: sles-gpdb-dev-11-beta
    input_mapping:
      bin_gpdb: bin_gpdb_suse11
      bin_plr: plr_gpdb_suse11_build
    output_mapping:
      plr_gppkg: plr_gpdb_suse11_release
    params:
      OSVER: suse11
      GPGBVER: GPDB-5.0.0
  - put: plr_gpdb_suse11_release
    params:
      file: plr_gpdb_suse11_release/plr-*.gppkg
